#! /usr/bin/env bash

mkdir -p tmp

if [ ! -x `which vagrant` ]
then
    echo "You need to install Vagrant from http://downloads.vagrantup.com/"
    exit
fi

O=`vagrant -v | grep 1.2`
if [ -z "$O" ]
then
    echo "Metron uses the vagrant-aws plugin, which requires Vagrant 1.2 or newer"
    echo "Please download a newer version of Vagrant from http://downloads.vagrantup.com"
    exit
fi

function check_plugin {
    O=`vagrant plugin list | grep $1`
    if [ -z "$O" ]
    then
        vagrant plugin install vagrant-aws
    fi
}

ensure_plugin "vagrant-aws"
ensure_plugin "vagrant-berkshelf"
ensure_plugin "vagrant-omnibus"

vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box

gem install berkshelf

if [ -x `which rbenv` ]
then
    rbenv rehash
fi

berks install
