#! /usr/bin/env bash

source ~/.rvm/scripts/rvm
rvm use 1.8.7
if [[ 0 -ne $? ]]
then
  rvm install 1.8.7
  rvm use 1.8.7
fi

rvm gemset create metron
rvm gemset use metron

gem install bundler
bundle install
mkdir -p tmp
